### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by FlavioGoncalves-Cayas** [jfversluis/Plugin.Maui.FormsMigration#1]
Hi Gerald,

I am trying to verify that migration of AppProperties works, but in my project it is not working. At least while debugging.
Tried with .net7 and .net8.

Am I missing something?

Could you please check this repository with a repro and point me in the right direction?

https://github.com/FlavioGoncalves-Cayas/XamarinToMauiProperties

**Comment by jfversluis** [comment]
Hey @FlavioGoncalves-Cayas!

I have been looking at this and can confirm that I see it's not working for iOS. Have you tested other platforms (as well)? 

If you follow the guide [here](https://learn.microsoft.com/dotnet/maui/migration/app-properties) and add that to your own application, does that work?

**Comment by FlavioGoncalves-Cayas** [comment]
I was testing it on Android. 
First I tried according to the docs. That didn't work and I stumbled across this Plugin, tried it, but had the same result.

**Comment by jfversluis** [comment]
I see what the problem is and was implementing a fix, but now I'm confused as suddenly it seems to start working also without my fix but on .NET 8. I'm trying to verify some things and will get back asap!

**Comment by FlavioGoncalves-Cayas** [comment]
Alright. Let me know if there is something I can help you with.

**Comment by jfversluis** [comment]
Could you try the preview 3 package that should be available in a few minutes and let me know?

That one is updated for .NET 8 so it only works for .NET 8 and newer now. I think this is mainly a bug in the .NET runtime. From my testing this should fix it, curious to hear your experience!

**Comment by jfversluis** [comment]
If you _really_ want I can also make it work for .NET 7 still with a little workaround

**Comment by FlavioGoncalves-Cayas** [comment]
I will give it a try.
For me personally, getting it to work with .NET 8 would be enough for now.

But I'm curious what you had to change though? Especially considering that the code from the docs did not work for me. Or does it also need your changes?

**Comment by jfversluis** [comment]
As mentioned this is more a bug in the .NET runtime, I suspect in this area: https://github.com/dotnet/runtime/pull/75541/files#r974375225 not sure if this is the exact thing I'm looking at but it's close.

So they accidentally changed something there in the path of the isolated storage. And now there was a discrepancy between where we are looking for this properties store file in legacy Xamarin and .NET. But, they fixed it! It seems that this didn't land in .NET 7 (yet).

While testing I decided to try .NET 8 and have my workaround in place, while I was stepping through it with the debugger I noticed that for .NET 8 it suddenly could find the file (where the properties are stored) and my workaround was no longer needed. So in the end, the only thing I had to do was update the library to use .NET 8 to bring in the fix in the .NET runtime.

Hope that makes sense!

**Comment by FlavioGoncalves-Cayas** [comment]
I have tried preview 3 with .net 8. On iOS it works flawlessly, but on Android it does not.

**Comment by jfversluis** [comment]
I think on Android something else might be going on and it deletes and reinstalls the app instead of updating it as it would do from the store. From my testing it looks like the properties store file gets deleted when you deploy the app.

**Comment by FlavioGoncalves-Cayas** [comment]
Either that or it maybe has to do with signing.
I built the Xamarin and Maui app in Release configuration and signed both of them with the same keystore. And voilà, it works as expected.
Sorry for the confusion and thanks for your fast response.

**Comment by jfversluis** [comment]
Perfect, glad I could help!

For the people finding this and needing it for .NET 7: you can read the file manually from the different location. This is the workaround code I came up with.

```csharp
static Stream GetPropertyStoreStream(IsolatedStorageFile? isolatedStorageFile)
{
  if (isolatedStorageFile is not null && isolatedStorageFile.FileExists(Constants.propertyStoreFile))
  {
	  return isolatedStorageFile.OpenFile(Constants.propertyStoreFile, FileMode.Open);
  }
  else
  {
	  var storeFilePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), ".isolated-storage", "PropertyStore.forms");
	  return File.OpenRead(storeFilePath);
  }
  
  throw new Exception("Could not locate legacy application property store for reading");
}
```

Add this to the `PropertiesDeserializer` on iOS and/or Android and make sure to get the file stream to be read like this: `using var stream = GetPropertyStoreStream(store);`. This does mean you need to pull in all this code into your own project.

This will see if it can read the property store file from the IsolatedStorage, if not, it will try to just read it from the filesystem and then follow the rest of the flow in code as per usual.

My recommendation would be to just update to .NET 8!

**Comment by Florin-Birgu** [comment]
I also had an issue in iOS. I ended up using migration documentation [example](https://learn.microsoft.com/en-us/dotnet/maui/migration/app-properties?view=net-maui-7.0) but I had to find the file manually in `documentsPath+"/.config/.isolated-storage/PropertyStore.forms"` and use a FileSteam to read it.
