### ISSUE TITLE
LegacySecureStorage.android: Remove(string) removes all entries

### ISSUE THREAD

**Issue by eerojaaskelainen** [jfversluis/Plugin.Maui.FormsMigration#2]
Greetings!
Thanks for your awesome work!

One issue I found with LegacySecureStorage:

https://github.com/jfversluis/Plugin.Maui.FormsMigration/blob/a73a639d23a18698a601c8cc3d509272e39bf49c/src/Plugin.Maui.FormsMigration/SecureStorage/LegacySecureStorage.android.cs#L50C27-L50C32

In Android, the "bool LegacySecureStorage.Remove(string)" command calls  Preferences.Clear(alias); which removes all SecureStorage entries.

Should id be more like "Preferences.Remove(key, alias);" ?

**Comment by jfversluis** [comment]
You're absolutely right! Seems like a copy/paste error or something. Opened a PR and will release that immediately. Thank you!
